### ISSUE TITLE
WiXToolsetNetCoreService.wxs File

### ISSUE THREAD

**Issue by vany0114** [z3ut/wix-toolset-net-core-service-example#1]
Hi, thanks for sharing this. How did you generate the `WiXToolsetNetCoreServiceProject` file?

**Comment by z3ut** [comment]
Hello, you're welcome.

It was some time ago and I don't remember all the details, but I think there is no file with this name, it is used as a reference name.

I added new OutputFile to .wixproj file in WiX project with reference ComponentGroupName="WiXToolsetNetCoreServiceProject" - this file would be created after project build. After that I used reference with same Id (ComponentGroupRef Id="WiXToolsetNetCoreServiceProject") to this file in Product.wxs.

If you have problems with specific step, you can describe your process and errors you got, I might be able to help.

**Comment by vany0114** [comment]
Sorry I meant the `WiXToolsetNetCoreService.wxs` file. 

Edit: nvm I saw is an output file defined in the build step, thanks!

**Comment by z3ut** [comment]
No worries, good luck.
